# This file contains specific services build and images for Windows Containers.
#
# MUST be used alongside "docker-compose.yml" in all windows container commands

version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 

  importleague-api:
    build:
      args:
        NODE_IMAGE: stefanscherer/node-windows:10

networks:
  default:
    external:
      name: nat